# script takes tpm file generated by quantification workflow and generates list of genes in tissues 
# It uses VennPainterCLI to generate .hf file and parse it to separate out tissue epecific and common genes
# It should be run in a dir where tissue specific data to be populated
# Change the Salmon output file path as necessary  

lines=(ARI JAG JUL LAN LER MAC MAT NOR STA)
tissues=(D F G R S V)
salmon_count=<path-to-salmon-data>
VennPainterpath=<path-to-vennpainter>

for line in "${lines[@]}"; do 
	mkdir ${line}; 
	for tissue in "${tissues[@]}"; do 
		mkdir ${tissue}
		if test -f ${salmon_count}${line}_${tissue}_quant/tpm.genes.mean.tsv; then 
			cut -f 1 ${salmon_count}${line}_${tissue}_quant/tpm.genes.mean.tsv > ${line}/${tissue}.tsv; 
			ls -1 ${line}/[DFGRSV].tsv > ${line}/${line}.txt; 
		fi
	done; 

	$VennPainterpath/VennpainterCLI_version/VennPainterCLI -i ${line}/${line}.txt -o ${line}/${line} -d h -t n; 

	for tissue in "${tissues[@]}"; do 
		if test -f ${line}/${line}.hf; then 
			grep "^${tissue} :" ${line}/${line}.hf | sed "s/${tissue}\s:\s//; s/\s/\"\n\"/g; s/^/\"/; s/$/\"/; s/\n\"\"//;" > ${line}/${line}_${tissue}_specific.txt; 
		fi
	done
done
